### ISSUE TITLE
Der Bereichstyp "copilot" ist nicht gültig

### ISSUE THREAD

**Issue by outline4** [kirby-tools/kirby-copilot#1]
This is my setup: 

"kirby": "4.3.1",
"php": "8.2.13",
"server": "LiteSpeed",

"name": "johannschopplich/copilot",
"version": "1.8.3"

I've tried multiple things, but this error: `Der Bereichstyp "copilot" ist nicht gültig` keeps popping up. 

I bought a license, but I can't enter it since I don't see the field. 

I hope it's a beginner mistake ;) 

Cheers  
Stefan

**Comment by outline4** [comment]
of course I've added 

    'johannschopplich.copilot' => [
        'providers' => [
            'openai' => [
                'apiKey' => 'xxxx',
                'model' => 'gpt-4o',
            ]
        ]
    ],


to the config.php

**Comment by johannschopplich** [comment]
Hi there!

Can you please send me your blueprint configuration and a minimum reproducible example? Without any context, I can't debug your error. 🙂 

Hint: The copilot is not a field, but a section. This is a basic setup:

```yml
sections:
  myCopilot:
    type: copilot
    field: content01
```

**Comment by outline4** [comment]
Hi, I've setup everything correctly. 

Two hours later, I walk into my office and see that it's working. 

Two hours is exactly the difference between my server time and the current time. 

It works, and I even registered it. Thanks for the quick reply!

**Comment by johannschopplich** [comment]
I'm not sure what the issue at hand was... Glad to hear it's working!

Feel free to each out if you encounter any other problems.
