### ISSUE TITLE
Check existing blocks for spelling errors or grammar

### ISSUE THREAD

**Issue by outline4** [kirby-tools/kirby-copilot#3]
Hi, 

I've expected copilot to be able to spell check all blocks or similar stuff with existing blocks or text fields.   
This would be highly beneficial. 

Other than this, it's doing a great job. 

Cheers
Stefan

**Comment by johannschopplich** [comment]
That's a proper feature request. As of now, blocks are only generated, not consumed by LLMs. This would require major refactors. Maybe part of the next version of Copilot.

**Comment by johannschopplich** [comment]
Spell-correction is not goal of this Kirby plugin. Howver, you can achieve something similar with the new [writer and textarea toolbar buttons](https://kirbycopilot.com/docs/usage/toolbar-buttons): By selecting your text and writing the prompt to check for grammar, you can achive your desired result:

> Check the selected text for spelling errors. Return the selected text with correct spelling (if applicable).
